<a href="https://colab.research.google.com/github/Levicute69/filtering-practice/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df_bike = pd.read_csv ('https://raw.githubusercontent.com/Levicute69/filtering-practice/main/RailsToTrails_National%20Count%20Data_week.csv')

In [3]:
df_bike.head()

,Timeframe,Week of,2019 counts (14 counters),2020 counts (14 counters),Change 2019-2020
0,Week 1,12/30/2020,68957.0,93654.0,36%
1,Week 2,1/6/2020,34778.0,46964.0,35%
2,Week 3,1/13/2020,32065.0,38302.0,19%
3,Week 4,1/20/2020,35016.0,41506.0,19%
4,Week 5,1/27/2020,33627.0,46335.0,38%

In [4]:
df_data = (df_bike [df_bike['Week of'] >= '31-July'])
df_data.head()

,Timeframe,Week of,2019 counts (14 counters),2020 counts (14 counters),Change 2019-2020
14,Week 15,4/6/2020,83893.0,107420.0,28%
15,Week 16,4/13/2020,71677.0,122291.0,71%
16,Week 17,4/20/2020,87834.0,106246.0,21%
17,Week 18,4/27/2020,88284.0,109459.0,24%
18,Week 19,5/4/2020,94980.0,109391.0,15%

In [5]:
df_fil = df_bike['Week of'] >='31-July'
df_fil.head()

0    False
1    False
2    False
3    False
4    False
Name: Week of, dtype: bool

In [6]:
df_bike[df_fil].head()

,Timeframe,Week of,2019 counts (14 counters),2020 counts (14 counters),Change 2019-2020
14,Week 15,4/6/2020,83893.0,107420.0,28%
15,Week 16,4/13/2020,71677.0,122291.0,71%
16,Week 17,4/20/2020,87834.0,106246.0,21%
17,Week 18,4/27/2020,88284.0,109459.0,24%
18,Week 19,5/4/2020,94980.0,109391.0,15%

In [7]:
df_bike.loc[df_fil, :].head()

,Timeframe,Week of,2019 counts (14 counters),2020 counts (14 counters),Change 2019-2020
14,Week 15,4/6/2020,83893.0,107420.0,28%
15,Week 16,4/13/2020,71677.0,122291.0,71%
16,Week 17,4/20/2020,87834.0,106246.0,21%
17,Week 18,4/27/2020,88284.0,109459.0,24%
18,Week 19,5/4/2020,94980.0,109391.0,15%

In [8]:
df = df_bike.loc[df_fil, :]
df['Week of'].value_counts()

4/6/2020     1
4/13/2020    1
9/21/2020    1
9/14/2020    1
9/7/2020     1
8/31/2020    1
8/24/2020    1
8/17/2020    1
8/10/2020    1
8/3/2020     1
7/27/2020    1
7/20/2020    1
7/13/2020    1
7/6/2020     1
6/29/2020    1
6/22/2020    1
6/15/2020    1
6/8/2020     1
6/1/2020     1
5/25/2020    1
5/18/2020    1
5/11/2020    1
5/4/2020     1
4/27/2020    1
4/20/2020    1
9/28/2020    1
Name: Week of, dtype: int64

In [9]:
df_bike['Change 2019-2020'].value_counts()

19%     4
32%     3
4%      2
15%     2
21%     2
25%     2
91%     2
59%     1
34%     1
14%     1
16%     1
17%     1
40%     1
-7%     1
31%     1
9%      1
75%     1
-3%     1
48%     1
36%     1
-16%    1
29%     1
35%     1
-41%    1
24%     1
71%     1
28%     1
80%     1
54%     1
287%    1
271%    1
-2%     1
45%     1
58%     1
38%     1
106%    1
Name: Change 2019-2020, dtype: int64

In [10]:
df_bike = df_bike.loc[df_fil, :]

In [11]:
df_bike['Change 2019-2020'].value_counts()

21%     2
15%     2
19%     2
28%     1
9%      1
59%     1
34%     1
14%     1
16%     1
4%      1
40%     1
-7%     1
32%     1
48%     1
-3%     1
71%     1
25%     1
17%     1
29%     1
-16%    1
-41%    1
24%     1
31%     1
Name: Change 2019-2020, dtype: int64

In [12]:
df.head()

,Timeframe,Week of,2019 counts (14 counters),2020 counts (14 counters),Change 2019-2020
14,Week 15,4/6/2020,83893.0,107420.0,28%
15,Week 16,4/13/2020,71677.0,122291.0,71%
16,Week 17,4/20/2020,87834.0,106246.0,21%
17,Week 18,4/27/2020,88284.0,109459.0,24%
18,Week 19,5/4/2020,94980.0,109391.0,15%

In [13]:
df_change = df_bike['Change 2019-2020'] >'100%'
df_change.head()

14    True
15    True
16    True
17    True
18    True
Name: Change 2019-2020, dtype: bool

In [14]:
df = (df_bike [df_bike['Change 2019-2020'] > '100%'])
df

,Timeframe,Week of,2019 counts (14 counters),2020 counts (14 counters),Change 2019-2020
14,Week 15,4/6/2020,83893.0,107420.0,28%
15,Week 16,4/13/2020,71677.0,122291.0,71%
16,Week 17,4/20/2020,87834.0,106246.0,21%
17,Week 18,4/27/2020,88284.0,109459.0,24%
18,Week 19,5/4/2020,94980.0,109391.0,15%
19,Week 20,5/11/2020,100251.0,119716.0,19%
22,Week 23,6/1/2020,97451.0,115580.0,19%
23,Week 24,6/8/2020,94747.0,122561.0,29%
24,Week 25,6/15/2020,87304.0,105924.0,21%
25,Week 26,6/22/2020,84230.0,97094.0,15%
26,Week 27,6/29/2020,68866.0,80405.0,17%
27,Week 28,7/6/2020,69626.0,87187.0,25%
28,Week 29,7/13/2020,64104.0,94974.0,48%
30,Week 31,7/27/2020,81182.0,88592.0,9%
31,Week 32,8/3/2020,71150.0,93785.0,32%
33,Week 34,8/17/2020,61826.0,86466.0,40%
34,Week 35,8/24/2020,69618.0,72144.0,4%
35,Week 36,8/31/2020,73657.0,85100.0,16%
36,Week 37,9/7/2020,64835.0,73695.0,14%
37,Week 38,9/14/2020,56589.0,75856.0,34%
38,Week 39,9/21/2020,51308.0,81451.0,59%
39,Week 40,9/28/2020,57862.0,75523.0,31%

In [15]:
df_change = df_bike['Change 2019-2020'] >'100%'
df_bike= df_bike.loc[df_change, :]
df_bike['Change 2019-2020'].value_counts(dropna = False)

21%    2
15%    2
19%    2
28%    1
32%    1
59%    1
34%    1
14%    1
16%    1
4%     1
40%    1
48%    1
9%     1
71%    1
25%    1
17%    1
29%    1
24%    1
31%    1
Name: Change 2019-2020, dtype: int64

In [18]:
df_bike = df_bike.loc[df_fil & df_change, :]

In [19]:
df_bike

,Timeframe,Week of,2019 counts (14 counters),2020 counts (14 counters),Change 2019-2020
14,Week 15,4/6/2020,83893.0,107420.0,28%
15,Week 16,4/13/2020,71677.0,122291.0,71%
16,Week 17,4/20/2020,87834.0,106246.0,21%
17,Week 18,4/27/2020,88284.0,109459.0,24%
18,Week 19,5/4/2020,94980.0,109391.0,15%
19,Week 20,5/11/2020,100251.0,119716.0,19%
22,Week 23,6/1/2020,97451.0,115580.0,19%
23,Week 24,6/8/2020,94747.0,122561.0,29%
24,Week 25,6/15/2020,87304.0,105924.0,21%
25,Week 26,6/22/2020,84230.0,97094.0,15%
26,Week 27,6/29/2020,68866.0,80405.0,17%
27,Week 28,7/6/2020,69626.0,87187.0,25%
28,Week 29,7/13/2020,64104.0,94974.0,48%
30,Week 31,7/27/2020,81182.0,88592.0,9%
31,Week 32,8/3/2020,71150.0,93785.0,32%
33,Week 34,8/17/2020,61826.0,86466.0,40%
34,Week 35,8/24/2020,69618.0,72144.0,4%
35,Week 36,8/31/2020,73657.0,85100.0,16%
36,Week 37,9/7/2020,64835.0,73695.0,14%
37,Week 38,9/14/2020,56589.0,75856.0,34%
38,Week 39,9/21/2020,51308.0,81451.0,59%
39,Week 40,9/28/2020,57862.0,75523.0,31%